trigger:
  - main
pr:
  - main

pool:
    vmImage: 'vs2017-win2016'
  
variables:
    - group: ADO-TF-Azure-Vnet-Int
  
  
  # Install Terraform extension to use this task https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks&ssr=false#overview
steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: 'Install Terraform 0.14.7'
    inputs:
      terraformVersion: 0.14.7
  # Terraform versions: https://releases.hashicorp.com/terraform/
  - powershell: |
     terraform init -backend-config="access_key=$(storage_access_key)" -no-color
    workingDirectory: $(build.sourcesdirectory)
    displayName: 'terraform init'
  
  - powershell: |
     terraform validate -json -no-color
    workingDirectory: $(build.sourcesdirectory)
    displayName: 'terraform validate'

  - powershell: |
      terraform plan -var client_secret="$(client_secret)" -var client_id="$(client_id)" -var subscription_id="$(subscription_id)" -var tenant_id="$(tenant_id)" -out application.tfplan -no-color
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))